apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    generation: 1
  labels:
    app: manageemployees-dplmnt
  name: manageemployees-dplmnt
  namespace: default
  spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: manageemployees-dplmnt
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: manageemployees-dplmnt
    spec:
      containers:
      - image: localhost:5000/manageemployees:${IMAGE_TAG}
        imagePullPolicy: IfNotPresent
        name: manageemployees
        ports:
        - containerPort: 9090
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  
  - lastTransitionTime: "2025-04-09T09:20:25Z"
    lastUpdateTime: "2025-04-09T09:20:26Z"
    message: ReplicaSet "manageemployees-dplmnt-694df78b5c" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
